### ISSUE TITLE
Create some wordpress.xml-files for testing.

### ISSUE THREAD

**Issue by thomasf** [thomasf/exitwp#18]
I'm having trouble maintaining this application due to the lack of tests.
A bunch of wordpress.xml's from different sources to verify that it's all working should do fine.

**Comment by davidak** [comment]
here you have an export of a fresh installed wordpress 4.2.2

[demosite.wordpress.2016-02-23.xml.zip](https://github.com/getnikola/nikola/files/143073/demosite.wordpress.2016-02-23.xml.zip)
