### ISSUE TITLE
No module name yaml??

### ISSUE THREAD

**Issue by smittie** [thomasf/exitwp#57]
I get the following error:

Traceback (most recent call last):
  File "exitwp.py", line 10, in <module>
    import yaml
ImportError: No module named yaml

What am I missing?

 -- Smittie

**Comment by kkolstad** [comment]
@smittie I'm on a mac and was able to fix this by doing installing python using homebrew and then installing the dependencies with `pip`:

```
brew install python
pip install pyyaml beautifulsoup4 html2text
python exitwp.py
```

Hope this helps.

**Comment by maxtheminimalist** [comment]
@smittie This solution worked for me: [http://stackoverflow.com/questions/20173535/exitwp-is-unable-to-import-pyyaml-module](http://stackoverflow.com/questions/20173535/exitwp-is-unable-to-import-pyyaml-module) Make sure you're in the directory with the xml files and paste the command.

**Comment by smittie** [comment]
Thanks everyone. Found another solution.

  ...Smittie

**Comment by interglobalmedia** [comment]
Hi,

I have the same issue and am on El Capitan. However, the stackoverflow solution does NOT work for me. Anyone else encounter that problem on El Capitan?
