### ISSUE TITLE
where is the build directory ?

### ISSUE THREAD

**Issue by icf20** [thomasf/exitwp#62]
> You should now have all the blogs converted into separate directories under the build directory

**Comment by gvansickle** [comment]
You cd into the `git` clone root and run `python exitwp.py`.  This creates the `build` directory there, under the clone's root dir.

**Comment by AndreaCirilloAC** [comment]
if you do not find it this probably means the process is not going on smoothly, since this folder is created at the end of the process, when calling the `write_jekill` function.
