### ISSUE TITLE
Export custom post type?

### ISSUE THREAD

**Issue by christopherisnow** [thomasf/exitwp#72]
I'm trying to export a WP site with the Portfolio Press theme: https://wptheming.com/portfolio-press/. Most of my content is saved as the custom post type "portfolio". They appear in the .xml file after exporting from WP.

But `exitwp.py` does not output the portfolio posts in /build. There are several lines at the end of the report in the command line `.Unknown item type :: portfolio`

How do I include this custom post type in the output?

**Comment by thomasf** [comment]
You have to add code which converts the portfolio item type.

**Comment by christopherisnow** [comment]
That solved it -- thanks very much!
